# Generated by Django 5.2.6 on 2025-09-19 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecity',
            name='notify_extreme_weather',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='favoritecity',
            name='notify_rain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favoritecity',
            name='temperature_threshold_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favoritecity',
            name='temperature_threshold_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='severe_weather_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weather_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email_type', models.CharField(max_length=50)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('temperature_high', 'High Temperature Alert'), ('temperature_low', 'Low Temperature Alert'), ('rain', 'Rain Alert'), ('storm', 'Storm Alert'), ('severe', 'Severe Weather Alert'), ('daily_summary', 'Daily Weather Summary')], max_length=20)),
                ('message', models.TextField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
