# Generated by Django 5.2.6 on 2025-09-29 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_remove_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favoritecity',
            name='notify_rain',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='favoritecity',
            name='temperature_threshold_high',
            field=models.FloatField(blank=True, default=35.0, null=True),
        ),
        migrations.AlterField(
            model_name='favoritecity',
            name='temperature_threshold_low',
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
    ]
